import {
  Signal, Prospect, Conversation, Meeting, ICP, AnalyticsOverview,
  DailyMetrics, OutreachAction, ConversationMessage
} from '@/types';

// ---- Mock Prospects ----
export const mockProspects: Prospect[] = [
  {
    id: 'p1',
    workspace_id: 'ws1',
    twitter_handle: '@sarahchen_tech',
    linkedin_url: null,
    email: 'sarah@techcorp.io',
    name: 'Sarah Chen',
    title: 'VP of Sales',
    company: 'TechCorp',
    industry: 'SaaS',
    location: 'San Francisco, CA',
    bio: 'Building the future of sales automation. Previously @Salesforce. Love hiking and coffee.',
    avatar_url: null,
    enrichment_data: { company_size: '50-200', funding: 'Series B' },
    icp_match_score: 92,
    signal_score: 87,
    stage: 'engaged',
    first_signal_at: '2026-03-10T14:30:00Z',
    last_signal_at: '2026-03-14T10:15:00Z',
    created_at: '2026-03-10T14:30:00Z',
    updated_at: '2026-03-14T10:15:00Z',
  },
  {
    id: 'p2',
    workspace_id: 'ws1',
    twitter_handle: '@mike_growthops',
    linkedin_url: null,
    email: null,
    name: 'Mike Rivera',
    title: 'Head of Growth',
    company: 'ScaleUp AI',
    industry: 'AI/ML',
    location: 'Austin, TX',
    bio: 'Growth @ ScaleUp AI | Ex-HubSpot | Obsessed with pipeline efficiency',
    avatar_url: null,
    enrichment_data: { company_size: '20-50', funding: 'Series A' },
    icp_match_score: 88,
    signal_score: 76,
    stage: 'warming',
    first_signal_at: '2026-03-12T09:00:00Z',
    last_signal_at: '2026-03-14T08:45:00Z',
    created_at: '2026-03-12T09:00:00Z',
    updated_at: '2026-03-14T08:45:00Z',
  },
  {
    id: 'p3',
    workspace_id: 'ws1',
    twitter_handle: '@jess_b2b',
    linkedin_url: null,
    email: 'jess@outbound.co',
    name: 'Jessica Brooks',
    title: 'CEO',
    company: 'Outbound.co',
    industry: 'Sales Tech',
    location: 'New York, NY',
    bio: 'CEO @Outbound.co | Helping B2B teams close faster | Angel investor',
    avatar_url: null,
    enrichment_data: { company_size: '10-20', funding: 'Seed' },
    icp_match_score: 95,
    signal_score: 91,
    stage: 'booking',
    first_signal_at: '2026-03-08T16:20:00Z',
    last_signal_at: '2026-03-14T11:30:00Z',
    created_at: '2026-03-08T16:20:00Z',
    updated_at: '2026-03-14T11:30:00Z',
  },
  {
    id: 'p4',
    workspace_id: 'ws1',
    twitter_handle: '@david_revops',
    linkedin_url: 'https://linkedin.com/in/david-park-revops',
    email: null,
    name: 'David Park',
    title: 'Revenue Operations Manager',
    company: 'CloudBase',
    industry: 'Cloud Infrastructure',
    location: 'Seattle, WA',
    bio: 'RevOps @ CloudBase | Data-driven sales nerd | Tableau + Salesforce',
    avatar_url: null,
    enrichment_data: { company_size: '200-500', funding: 'Series C' },
    icp_match_score: 78,
    signal_score: 65,
    stage: 'detected',
    first_signal_at: '2026-03-14T07:00:00Z',
    last_signal_at: '2026-03-14T07:00:00Z',
    created_at: '2026-03-14T07:00:00Z',
    updated_at: '2026-03-14T07:00:00Z',
  },
  {
    id: 'p5',
    workspace_id: 'ws1',
    twitter_handle: '@lisa_saas',
    linkedin_url: 'https://linkedin.com/in/lisa-nguyen-sales',
    email: 'lisa@dataflow.io',
    name: 'Lisa Nguyen',
    title: 'Director of Sales',
    company: 'DataFlow',
    industry: 'Data Analytics',
    location: 'Chicago, IL',
    bio: 'Sales leader @ DataFlow | Building modern sales teams | Speaker',
    avatar_url: null,
    enrichment_data: { company_size: '100-200', funding: 'Series B' },
    icp_match_score: 85,
    signal_score: 82,
    stage: 'booked',
    first_signal_at: '2026-03-05T12:00:00Z',
    last_signal_at: '2026-03-13T15:45:00Z',
    created_at: '2026-03-05T12:00:00Z',
    updated_at: '2026-03-13T15:45:00Z',
  },
  {
    id: 'p6',
    workspace_id: 'ws1',
    twitter_handle: null,
    linkedin_url: 'https://linkedin.com/in/alex-morgan-cro',
    email: 'alex@revgrowth.io',
    name: 'Alex Morgan',
    title: 'Chief Revenue Officer',
    company: 'RevGrowth',
    industry: 'SaaS',
    location: 'Denver, CO',
    bio: 'CRO at RevGrowth | 15+ years in B2B sales | Building revenue machines with AI | Ex-Oracle, Ex-Gong',
    avatar_url: null,
    enrichment_data: { company_size: '50-200', funding: 'Series B' },
    icp_match_score: 94,
    signal_score: 89,
    stage: 'warming',
    first_signal_at: '2026-03-13T11:00:00Z',
    last_signal_at: '2026-03-14T14:20:00Z',
    created_at: '2026-03-13T11:00:00Z',
    updated_at: '2026-03-14T14:20:00Z',
  },
  {
    id: 'p7',
    workspace_id: 'ws1',
    twitter_handle: null,
    linkedin_url: 'https://linkedin.com/in/priya-sharma-gtm',
    email: null,
    name: 'Priya Sharma',
    title: 'VP Go-to-Market',
    company: 'NexusAI',
    industry: 'AI/ML',
    location: 'Boston, MA',
    bio: 'VP GTM @ NexusAI | Scaling from $5M to $50M ARR | Ex-Drift, Ex-Segment | Harvard MBA',
    avatar_url: null,
    enrichment_data: { company_size: '100-200', funding: 'Series C' },
    icp_match_score: 90,
    signal_score: 85,
    stage: 'engaged',
    first_signal_at: '2026-03-11T09:30:00Z',
    last_signal_at: '2026-03-14T16:45:00Z',
    created_at: '2026-03-11T09:30:00Z',
    updated_at: '2026-03-14T16:45:00Z',
  },
  {
    id: 'p8',
    workspace_id: 'ws1',
    twitter_handle: '@tom_pipeline',
    linkedin_url: 'https://linkedin.com/in/tom-chen-sales',
    email: 'tom@cloudpipe.io',
    name: 'Tom Chen',
    title: 'Head of Sales Development',
    company: 'CloudPipe',
    industry: 'Cloud Infrastructure',
    location: 'San Jose, CA',
    bio: 'Leading SDR team @ CloudPipe | Signal-driven outbound believer | Previously at Gong & Clari',
    avatar_url: null,
    enrichment_data: { company_size: '200-500', funding: 'Series C' },
    icp_match_score: 87,
    signal_score: 78,
    stage: 'detected',
    first_signal_at: '2026-03-14T13:00:00Z',
    last_signal_at: '2026-03-14T13:00:00Z',
    created_at: '2026-03-14T13:00:00Z',
    updated_at: '2026-03-14T13:00:00Z',
  },
];

// ---- Mock Signals ----
export const mockSignals: Signal[] = [
  {
    id: 's1',
    prospect_id: 'p1',
    workspace_id: 'ws1',
    platform: 'twitter',
    signal_type: 'pain_point',
    raw_data: {},
    score: 87,
    tier: 'hot',
    content_preview: '"Our SDR team is spending 4+ hours a day on manual prospecting. There has to be a better way. Anyone using AI for outbound?"',
    source_url: 'https://x.com/sarahchen_tech/status/123',
    triggered_action: 'outreach_started',
    is_dismissed: false,
    detected_at: '2026-03-14T10:15:00Z',
    created_at: '2026-03-14T10:15:00Z',
    prospect: mockProspects[0],
  },
  {
    id: 's2',
    prospect_id: 'p2',
    workspace_id: 'ws1',
    platform: 'twitter',
    signal_type: 'competitor_engagement',
    raw_data: {},
    score: 76,
    tier: 'warm',
    content_preview: 'Liked and replied to @AutoReach tweet about signal-driven outbound',
    source_url: 'https://x.com/mike_growthops/status/456',
    triggered_action: 'warmup_started',
    is_dismissed: false,
    detected_at: '2026-03-14T08:45:00Z',
    created_at: '2026-03-14T08:45:00Z',
    prospect: mockProspects[1],
  },
  {
    id: 's3',
    prospect_id: 'p3',
    workspace_id: 'ws1',
    platform: 'twitter',
    signal_type: 'buying_language',
    raw_data: {},
    score: 91,
    tier: 'hot',
    content_preview: '"Looking for recommendations: best AI SDR tools that actually work on X/Twitter? We\'re evaluating options for Q2."',
    source_url: 'https://x.com/jess_b2b/status/789',
    triggered_action: 'outreach_started',
    is_dismissed: false,
    detected_at: '2026-03-14T11:30:00Z',
    created_at: '2026-03-14T11:30:00Z',
    prospect: mockProspects[2],
  },
  {
    id: 's4',
    prospect_id: 'p4',
    workspace_id: 'ws1',
    platform: 'twitter',
    signal_type: 'keyword_mention',
    raw_data: {},
    score: 65,
    tier: 'warm',
    content_preview: 'Thread: "How we rebuilt our outbound motion to focus on intent signals instead of volume..."',
    source_url: 'https://x.com/david_revops/status/012',
    triggered_action: null,
    is_dismissed: false,
    detected_at: '2026-03-14T07:00:00Z',
    created_at: '2026-03-14T07:00:00Z',
    prospect: mockProspects[3],
  },
  {
    id: 's5',
    prospect_id: 'p3',
    workspace_id: 'ws1',
    platform: 'twitter',
    signal_type: 'competitor_follow',
    raw_data: {},
    score: 72,
    tier: 'warm',
    content_preview: 'Started following @AutoReach, @Trigify, and @ValleyAI',
    source_url: null,
    triggered_action: null,
    is_dismissed: false,
    detected_at: '2026-03-13T16:20:00Z',
    created_at: '2026-03-13T16:20:00Z',
    prospect: mockProspects[2],
  },
  {
    id: 's6',
    prospect_id: 'p5',
    workspace_id: 'ws1',
    platform: 'twitter',
    signal_type: 'hashtag_match',
    raw_data: {},
    score: 82,
    tier: 'hot',
    content_preview: '#lookingfor an AI-powered tool to help my team book more meetings automatically. Cold email is dying.',
    source_url: 'https://x.com/lisa_saas/status/345',
    triggered_action: 'outreach_started',
    is_dismissed: false,
    detected_at: '2026-03-13T15:45:00Z',
    created_at: '2026-03-13T15:45:00Z',
    prospect: mockProspects[4],
  },
  {
    id: 's7',
    prospect_id: 'p1',
    workspace_id: 'ws1',
    platform: 'twitter',
    signal_type: 'thread_participation',
    raw_data: {},
    score: 68,
    tier: 'warm',
    content_preview: 'Joined thread discussing "The future of SDRs in the age of AI agents"',
    source_url: 'https://x.com/sarahchen_tech/status/678',
    triggered_action: null,
    is_dismissed: false,
    detected_at: '2026-03-12T14:30:00Z',
    created_at: '2026-03-12T14:30:00Z',
    prospect: mockProspects[0],
  },
  {
    id: 's8',
    prospect_id: 'p2',
    workspace_id: 'ws1',
    platform: 'twitter',
    signal_type: 'post_engagement',
    raw_data: {},
    score: 45,
    tier: 'warm',
    content_preview: 'Liked 3 posts about "intent-based selling" in the last 24 hours',
    source_url: null,
    triggered_action: null,
    is_dismissed: false,
    detected_at: '2026-03-12T09:00:00Z',
    created_at: '2026-03-12T09:00:00Z',
    prospect: mockProspects[1],
  },
  // LinkedIn Signals
  {
    id: 's9',
    prospect_id: 'p6',
    workspace_id: 'ws1',
    platform: 'linkedin',
    signal_type: 'profile_view',
    raw_data: { view_count: 3, viewer_title: 'CRO', company: 'RevGrowth' },
    score: 82,
    tier: 'hot',
    content_preview: 'Viewed your profile 3 times in the last 48 hours. CRO at RevGrowth (Series B, 50-200 employees)',
    source_url: 'https://linkedin.com/in/alex-morgan-cro',
    triggered_action: 'connection_request_sent',
    is_dismissed: false,
    detected_at: '2026-03-14T14:20:00Z',
    created_at: '2026-03-14T14:20:00Z',
    prospect: mockProspects[5],
  },
  {
    id: 's10',
    prospect_id: 'p7',
    workspace_id: 'ws1',
    platform: 'linkedin',
    signal_type: 'job_change',
    raw_data: { old_role: 'Director of Sales', new_role: 'VP Go-to-Market', company: 'NexusAI' },
    score: 88,
    tier: 'hot',
    content_preview: 'Recently promoted to VP Go-to-Market at NexusAI. Previously Director of Sales at Drift.',
    source_url: 'https://linkedin.com/in/priya-sharma-gtm',
    triggered_action: 'connection_request_sent',
    is_dismissed: false,
    detected_at: '2026-03-14T16:45:00Z',
    created_at: '2026-03-14T16:45:00Z',
    prospect: mockProspects[6],
  },
  {
    id: 's11',
    prospect_id: 'p7',
    workspace_id: 'ws1',
    platform: 'linkedin',
    signal_type: 'linkedin_engagement',
    raw_data: { engagement_type: 'comment', post_topic: 'AI SDR tools' },
    score: 79,
    tier: 'warm',
    content_preview: 'Commented on post: "We need to rethink how SDR teams operate. AI isn\'t replacing them — it\'s giving them superpowers. Looking at tools that detect buying signals in real-time."',
    source_url: 'https://linkedin.com/feed/update/urn:li:activity:7890123456',
    triggered_action: null,
    is_dismissed: false,
    detected_at: '2026-03-14T12:30:00Z',
    created_at: '2026-03-14T12:30:00Z',
    prospect: mockProspects[6],
  },
  {
    id: 's12',
    prospect_id: 'p6',
    workspace_id: 'ws1',
    platform: 'linkedin',
    signal_type: 'company_growth',
    raw_data: { growth_type: 'hiring', roles: ['SDR', 'AE', 'Sales Manager'], count: 5 },
    score: 74,
    tier: 'warm',
    content_preview: 'RevGrowth is hiring 5 sales roles (2 SDRs, 2 AEs, 1 Sales Manager). Indicates scaling outbound team.',
    source_url: 'https://linkedin.com/company/revgrowth/jobs',
    triggered_action: null,
    is_dismissed: false,
    detected_at: '2026-03-13T11:00:00Z',
    created_at: '2026-03-13T11:00:00Z',
    prospect: mockProspects[5],
  },
  {
    id: 's13',
    prospect_id: 'p8',
    workspace_id: 'ws1',
    platform: 'linkedin',
    signal_type: 'competitor_follower',
    raw_data: { competitor: 'AutoReach', action: 'followed_company' },
    score: 70,
    tier: 'warm',
    content_preview: 'Started following AutoReach and Trigify company pages on LinkedIn. Active in sales automation community.',
    source_url: 'https://linkedin.com/in/tom-chen-sales',
    triggered_action: null,
    is_dismissed: false,
    detected_at: '2026-03-14T13:00:00Z',
    created_at: '2026-03-14T13:00:00Z',
    prospect: mockProspects[7],
  },
  {
    id: 's14',
    prospect_id: 'p8',
    workspace_id: 'ws1',
    platform: 'linkedin',
    signal_type: 'linkedin_engagement',
    raw_data: { engagement_type: 'share', post_topic: 'outbound sales' },
    score: 66,
    tier: 'warm',
    content_preview: 'Shared article: "Why Cold Outbound is Dead and Signal-Based Selling is the Future" with comment: "This is exactly the shift we\'re making at CloudPipe."',
    source_url: 'https://linkedin.com/feed/update/urn:li:activity:7890123457',
    triggered_action: null,
    is_dismissed: false,
    detected_at: '2026-03-13T15:00:00Z',
    created_at: '2026-03-13T15:00:00Z',
    prospect: mockProspects[7],
  },
];

// ---- Mock Conversations ----
export const mockConversations: Conversation[] = [
  {
    id: 'c1',
    prospect_id: 'p1',
    workspace_id: 'ws1',
    platform: 'twitter',
    status: 'active',
    messages: [
      { id: 'm1', role: 'ai', content: 'Hey Sarah! Saw your tweet about SDR team spending 4+ hours on manual prospecting. We had the exact same problem and found a way to cut that down to 30 min using signal-based targeting. Would love to share what worked.', sent_at: '2026-03-14T10:30:00Z', status: 'delivered' },
      { id: 'm2', role: 'prospect', content: 'Oh interesting! Yeah it\'s been a real pain point. What approach did you take?', sent_at: '2026-03-14T11:15:00Z', status: 'read' },
      { id: 'm3', role: 'ai', content: 'We built a system that monitors X for buying signals — pain point tweets, competitor engagement, evaluation language — then automatically warms up and reaches out at the right moment. Way more effective than cold outbound. Want me to show you a quick demo?', sent_at: '2026-03-14T11:20:00Z', status: 'delivered' },
    ],
    context: { signal_trigger: 'pain_point_tweet' },
    is_ai_managed: true,
    started_at: '2026-03-14T10:30:00Z',
    last_message_at: '2026-03-14T11:20:00Z',
    created_at: '2026-03-14T10:30:00Z',
    updated_at: '2026-03-14T11:20:00Z',
    prospect: mockProspects[0],
  },
  {
    id: 'c2',
    prospect_id: 'p3',
    workspace_id: 'ws1',
    platform: 'twitter',
    status: 'booked',
    messages: [
      { id: 'm4', role: 'ai', content: 'Hi Jessica! Noticed you\'re evaluating AI SDR tools for Q2. We focus specifically on X/Twitter outreach with signal detection. Happy to chat if you\'re comparing options?', sent_at: '2026-03-14T11:45:00Z', status: 'read' },
      { id: 'm5', role: 'prospect', content: 'Yes! We\'ve been looking at a few. What makes yours different from AutoReach?', sent_at: '2026-03-14T12:30:00Z', status: 'read' },
      { id: 'm6', role: 'ai', content: 'Great question. While AutoReach is more DFY, we\'re self-serve with more control over targeting and messaging. Plus real-time signal detection vs batch processing. Would a 15-min demo be worth it?', sent_at: '2026-03-14T12:35:00Z', status: 'read' },
      { id: 'm7', role: 'prospect', content: 'Sure, I\'m free Tuesday or Wednesday afternoon next week', sent_at: '2026-03-14T13:00:00Z', status: 'read' },
      { id: 'm8', role: 'ai', content: 'How about Tuesday at 2pm PT? Here\'s a link to grab the slot: https://calendly.com/demo/ai-buyer-engine', sent_at: '2026-03-14T13:05:00Z', status: 'delivered' },
    ],
    context: { signal_trigger: 'buying_language' },
    is_ai_managed: true,
    started_at: '2026-03-14T11:45:00Z',
    last_message_at: '2026-03-14T13:05:00Z',
    created_at: '2026-03-14T11:45:00Z',
    updated_at: '2026-03-14T13:05:00Z',
    prospect: mockProspects[2],
  },
  {
    id: 'c3',
    prospect_id: 'p5',
    workspace_id: 'ws1',
    platform: 'twitter',
    status: 'booked',
    messages: [
      { id: 'm9', role: 'ai', content: 'Hi Lisa! Your tweet about looking for AI meeting booking tools resonated. Cold email IS dying — we\'re seeing 3x better response rates from warm social outreach. Want to see how?', sent_at: '2026-03-13T16:00:00Z', status: 'read' },
      { id: 'm10', role: 'prospect', content: 'Sounds relevant. We\'re looking to revamp our outbound for Q2. Tell me more?', sent_at: '2026-03-13T17:30:00Z', status: 'read' },
      { id: 'm11', role: 'ai', content: 'We detect buying signals on X (like your tweet!) and automatically engage prospects with personalized warm-up before DMs. Already booked 20+ meetings for beta users. Free to chat this week?', sent_at: '2026-03-13T17:35:00Z', status: 'read' },
      { id: 'm12', role: 'prospect', content: 'Let\'s do Thursday at 11am CT', sent_at: '2026-03-13T18:00:00Z', status: 'read' },
      { id: 'm13', role: 'ai', content: 'Booked! Thursday 11am CT it is. Sending you a calendar invite now. Looking forward to it, Lisa! 🎯', sent_at: '2026-03-13T18:05:00Z', status: 'delivered' },
    ],
    context: { signal_trigger: 'hashtag_match' },
    is_ai_managed: true,
    started_at: '2026-03-13T16:00:00Z',
    last_message_at: '2026-03-13T18:05:00Z',
    created_at: '2026-03-13T16:00:00Z',
    updated_at: '2026-03-13T18:05:00Z',
    prospect: mockProspects[4],
  },
  // LinkedIn Conversations
  {
    id: 'c4',
    prospect_id: 'p6',
    workspace_id: 'ws1',
    platform: 'linkedin',
    status: 'active',
    messages: [
      { id: 'm14', role: 'ai', content: 'Hi Alex — noticed you\'ve been checking out our profile. As a CRO scaling a sales team, you might find our signal-based approach interesting. We detect buying intent on social platforms and automate warm outreach. Would love to connect!', sent_at: '2026-03-14T14:30:00Z', status: 'delivered' },
      { id: 'm15', role: 'prospect', content: 'Thanks for reaching out! Yes, we\'re actively looking for tools to make our SDR team more efficient. What platforms do you cover?', sent_at: '2026-03-14T15:45:00Z', status: 'read' },
      { id: 'm16', role: 'ai', content: 'We cover both X/Twitter and LinkedIn for signal detection — things like profile views, post engagement, job changes, and buying language. Then we automate personalized warm-up sequences. Our beta users are seeing 3x response rates vs cold outreach. Happy to show you a quick demo?', sent_at: '2026-03-14T15:50:00Z', status: 'delivered' },
    ],
    context: { signal_trigger: 'profile_view' },
    is_ai_managed: true,
    started_at: '2026-03-14T14:30:00Z',
    last_message_at: '2026-03-14T15:50:00Z',
    created_at: '2026-03-14T14:30:00Z',
    updated_at: '2026-03-14T15:50:00Z',
    prospect: mockProspects[5],
  },
  {
    id: 'c5',
    prospect_id: 'p7',
    workspace_id: 'ws1',
    platform: 'linkedin',
    status: 'active',
    messages: [
      { id: 'm17', role: 'ai', content: 'Congrats on the VP GTM role at NexusAI, Priya! 🎉 Saw your comment about AI giving SDR teams superpowers — couldn\'t agree more. We\'re building exactly that: real-time buying signal detection + automated warm outreach. Would love to connect and share what we\'re seeing.', sent_at: '2026-03-14T17:00:00Z', status: 'read' },
      { id: 'm18', role: 'prospect', content: 'Thanks! It\'s been an exciting transition. I\'m definitely interested — we\'re rebuilding our entire outbound motion. What makes your approach different from the existing tools?', sent_at: '2026-03-14T18:15:00Z', status: 'read' },
    ],
    context: { signal_trigger: 'job_change' },
    is_ai_managed: true,
    started_at: '2026-03-14T17:00:00Z',
    last_message_at: '2026-03-14T18:15:00Z',
    created_at: '2026-03-14T17:00:00Z',
    updated_at: '2026-03-14T18:15:00Z',
    prospect: mockProspects[6],
  },
];

// ---- Mock Meetings ----
export const mockMeetings: Meeting[] = [
  {
    id: 'mt1',
    prospect_id: 'p3',
    workspace_id: 'ws1',
    calendar_event_id: 'cal_123',
    meeting_type: 'discovery',
    title: 'Discovery Call - Jessica Brooks (Outbound.co)',
    scheduled_at: '2026-03-17T21:00:00Z', // Tue 2pm PT
    duration_min: 15,
    status: 'scheduled',
    meeting_link: 'https://meet.google.com/abc-defg-hij',
    pre_meeting_brief: {
      prospect_summary: 'CEO of Outbound.co (10-20 employees, Seed stage). Actively evaluating AI SDR tools for Q2.',
      recent_activity: ['Tweeted about evaluating AI SDR tools', 'Followed AutoReach, Trigify, ValleyAI', 'Engaged with 5+ sales automation posts this week'],
      signal_history: ['Buying language signal (score: 91)', 'Competitor follow signal (score: 72)'],
      talking_points: ['Self-serve vs DFY comparison with AutoReach', 'Signal detection accuracy', 'X/Twitter focus and differentiation', 'Pricing flexibility for small teams'],
      mutual_connections: ['@sales_thought_leader', '@b2b_community'],
    },
    booked_at: '2026-03-14T13:05:00Z',
    created_at: '2026-03-14T13:05:00Z',
    prospect: mockProspects[2],
  },
  {
    id: 'mt2',
    prospect_id: 'p5',
    workspace_id: 'ws1',
    calendar_event_id: 'cal_456',
    meeting_type: 'demo',
    title: 'Product Demo - Lisa Nguyen (DataFlow)',
    scheduled_at: '2026-03-19T17:00:00Z', // Thu 11am CT
    duration_min: 30,
    status: 'confirmed',
    meeting_link: 'https://meet.google.com/klm-nopq-rst',
    pre_meeting_brief: {
      prospect_summary: 'Director of Sales at DataFlow (100-200 employees, Series B). Looking to revamp outbound for Q2.',
      recent_activity: ['Posted about AI meeting booking tools', 'Active in sales automation discussions', 'Shared article on intent-based selling'],
      signal_history: ['Hashtag match signal (score: 82)', 'Multiple engagement signals this week'],
      talking_points: ['Cold email replacement strategy', 'Integration with existing sales stack', 'Team onboarding and adoption', 'ROI expectations and timeline'],
      mutual_connections: [],
    },
    booked_at: '2026-03-13T18:05:00Z',
    created_at: '2026-03-13T18:05:00Z',
    prospect: mockProspects[4],
  },
];

// ---- Mock ICPs ----
export const mockICPs: ICP[] = [
  {
    id: 'icp1',
    workspace_id: 'ws1',
    name: 'B2B SaaS Sales Leaders',
    criteria: {
      industries: ['SaaS', 'Software', 'Technology'],
      company_sizes: ['10-50', '50-200', '200-500'],
      roles: ['VP Sales', 'Head of Sales', 'Director of Sales', 'Head of Growth', 'CEO'],
      seniority_levels: ['Director', 'VP', 'C-Level'],
      keywords: ['outbound', 'SDR', 'pipeline', 'prospecting', 'sales automation', 'AI SDR'],
      locations: ['United States', 'Canada', 'United Kingdom'],
      tech_stack: ['Salesforce', 'HubSpot', 'Apollo', 'Outreach', 'Salesloft'],
    },
    negative_filters: [
      { type: 'company', value: 'AutoReach' },
      { type: 'company', value: 'Trigify' },
      { type: 'keyword', value: 'student' },
    ],
    is_active: true,
    created_at: '2026-03-01T00:00:00Z',
    updated_at: '2026-03-14T00:00:00Z',
  },
  {
    id: 'icp2',
    workspace_id: 'ws1',
    name: 'Sales Agency Owners',
    criteria: {
      industries: ['Marketing Agency', 'Sales Consulting', 'Business Services'],
      company_sizes: ['1-10', '10-50'],
      roles: ['Founder', 'CEO', 'Owner', 'Managing Director'],
      seniority_levels: ['C-Level', 'Founder'],
      keywords: ['sales agency', 'outbound agency', 'lead generation', 'client acquisition'],
      locations: ['United States', 'United Kingdom', 'Australia'],
      tech_stack: ['GoHighLevel', 'HubSpot', 'Pipedrive'],
    },
    negative_filters: [
      { type: 'keyword', value: 'freelancer' },
    ],
    is_active: true,
    created_at: '2026-03-05T00:00:00Z',
    updated_at: '2026-03-12T00:00:00Z',
  },
];

// ---- Mock Outreach Actions ----
export const mockOutreachActions: OutreachAction[] = [
  { id: 'oa1', conversation_id: null, prospect_id: 'p2', workspace_id: 'ws1', action_type: 'like', platform: 'twitter', content: null, status: 'executed', scheduled_at: '2026-03-12T10:00:00Z', executed_at: '2026-03-12T10:01:00Z', error_message: null, created_at: '2026-03-12T10:00:00Z' },
  { id: 'oa2', conversation_id: null, prospect_id: 'p2', workspace_id: 'ws1', action_type: 'follow', platform: 'twitter', content: null, status: 'executed', scheduled_at: '2026-03-12T14:00:00Z', executed_at: '2026-03-12T14:02:00Z', error_message: null, created_at: '2026-03-12T14:00:00Z' },
  { id: 'oa3', conversation_id: null, prospect_id: 'p2', workspace_id: 'ws1', action_type: 'reply', platform: 'twitter', content: 'Great point about intent signals! We\'ve seen similar results when we shifted from volume to quality.', status: 'executed', scheduled_at: '2026-03-13T09:00:00Z', executed_at: '2026-03-13T09:03:00Z', error_message: null, created_at: '2026-03-13T09:00:00Z' },
  { id: 'oa4', conversation_id: null, prospect_id: 'p4', workspace_id: 'ws1', action_type: 'like', platform: 'twitter', content: null, status: 'pending', scheduled_at: '2026-03-14T15:00:00Z', executed_at: null, error_message: null, created_at: '2026-03-14T12:00:00Z' },
  { id: 'oa5', conversation_id: 'c1', prospect_id: 'p1', workspace_id: 'ws1', action_type: 'dm', platform: 'twitter', content: 'Hey Sarah! Saw your tweet...', status: 'executed', scheduled_at: '2026-03-14T10:30:00Z', executed_at: '2026-03-14T10:30:00Z', error_message: null, created_at: '2026-03-14T10:30:00Z' },
  // LinkedIn Outreach Actions
  { id: 'oa6', conversation_id: null, prospect_id: 'p6', workspace_id: 'ws1', action_type: 'connect', platform: 'linkedin', content: 'Hi Alex — noticed you\'ve been checking out our profile...', status: 'executed', scheduled_at: '2026-03-14T14:25:00Z', executed_at: '2026-03-14T14:30:00Z', error_message: null, created_at: '2026-03-14T14:25:00Z' },
  { id: 'oa7', conversation_id: null, prospect_id: 'p7', workspace_id: 'ws1', action_type: 'connect', platform: 'linkedin', content: 'Congrats on the VP GTM role at NexusAI, Priya!', status: 'executed', scheduled_at: '2026-03-14T16:55:00Z', executed_at: '2026-03-14T17:00:00Z', error_message: null, created_at: '2026-03-14T16:55:00Z' },
  { id: 'oa8', conversation_id: null, prospect_id: 'p8', workspace_id: 'ws1', action_type: 'view', platform: 'linkedin', content: null, status: 'executed', scheduled_at: '2026-03-14T13:10:00Z', executed_at: '2026-03-14T13:10:00Z', error_message: null, created_at: '2026-03-14T13:10:00Z' },
  { id: 'oa9', conversation_id: null, prospect_id: 'p8', workspace_id: 'ws1', action_type: 'like', platform: 'linkedin', content: null, status: 'pending', scheduled_at: '2026-03-14T16:00:00Z', executed_at: null, error_message: null, created_at: '2026-03-14T13:15:00Z' },
  { id: 'oa10', conversation_id: 'c4', prospect_id: 'p6', workspace_id: 'ws1', action_type: 'dm', platform: 'linkedin', content: 'We cover both X/Twitter and LinkedIn...', status: 'executed', scheduled_at: '2026-03-14T15:50:00Z', executed_at: '2026-03-14T15:50:00Z', error_message: null, created_at: '2026-03-14T15:50:00Z' },
];

// ---- Mock Analytics ----
export const mockDailyMetrics: DailyMetrics[] = [
  { workspace_id: 'ws1', date: '2026-03-08', signals_detected: 12, outreach_sent: 3, responses_received: 1, meetings_booked: 0, meetings_completed: 0 },
  { workspace_id: 'ws1', date: '2026-03-09', signals_detected: 18, outreach_sent: 5, responses_received: 2, meetings_booked: 0, meetings_completed: 0 },
  { workspace_id: 'ws1', date: '2026-03-10', signals_detected: 22, outreach_sent: 7, responses_received: 3, meetings_booked: 1, meetings_completed: 0 },
  { workspace_id: 'ws1', date: '2026-03-11', signals_detected: 15, outreach_sent: 4, responses_received: 2, meetings_booked: 0, meetings_completed: 1 },
  { workspace_id: 'ws1', date: '2026-03-12', signals_detected: 28, outreach_sent: 8, responses_received: 4, meetings_booked: 1, meetings_completed: 0 },
  { workspace_id: 'ws1', date: '2026-03-13', signals_detected: 31, outreach_sent: 10, responses_received: 5, meetings_booked: 2, meetings_completed: 1 },
  { workspace_id: 'ws1', date: '2026-03-14', signals_detected: 25, outreach_sent: 6, responses_received: 3, meetings_booked: 1, meetings_completed: 0 },
];

export const mockAnalytics: AnalyticsOverview = {
  total_signals: 198,
  total_prospects: 56,
  active_conversations: 12,
  meetings_booked: 7,
  meetings_completed: 3,
  signal_to_meeting_rate: 3.5,
  pipeline_stages: {
    detected: 22,
    warming: 16,
    engaged: 8,
    booking: 4,
    booked: 3,
    converted: 2,
    lost: 1,
  },
  daily_metrics: mockDailyMetrics,
};
